name: Hello World # The name of the workflow

on:
    workflow_dispatch: # Allows manual triggering of the workflow

jobs: # The jobs that will be run
    say-hello-inline-bash: # The ID of the job
        runs-on: ubuntu-24.04 # The operating system on which to run the job
        steps: # The steps that will be run in the job
            - run: echo "Hello from an inline bash script in a GitHub Action Workflow!"
